App\Entity\Plato:
  attributes:
    id:
      groups: ['restaurante']
    nombre:
      groups: ['restaurante']
    descripcion:
      groups: ['restaurante']
    imgUrl:
      groups: ['restaurante']
    precio:
      groups: ['restaurante']
    alergenos:
      groups: ['restaurante']