App\Entity\Restaurante:
  attributes:
    id:
      groups: ['restaurante', 'res_filtered']
    nombre:
      groups: ['restaurante','res_filtered']
    logo_url:
      groups: ['restaurante','res_filtered']
    imagenUrl:
      groups: ['restaurante']
    descripcion:
      groups: ['restaurante']
    destacado:
      groups: ['restaurante']
    platos:
      groups: ['restaurante']
    horarios:
      groups: []
    categorias:
      groups: [ 'res_filtered']
    municipio:
      groups: []


